name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  node-tests:
    strategy:
      fail-fast: false
      matrix:
        node_version: ["14", "16", "18"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Bootstrap
        run: |
          npm install

      - name: Unit tests
        run: npm run test
